export const authConstant ={
    LOGIN_REQUEST:"LOGIN_REQUEST",
    LOGIN_FALIURE:"LOGIN_FALIURE",
    LOGIN_SUCCESS:"LOGIN_SUCCESS",
    LOGOUT_REQUEST:"LOGOUT_REQUEST",
    LOGOUT_SUCCESS:"LOGOUT_SUCCESS",
    LOGOUT_FALIURE:"LOGOUT_FALIURE",

}


export const userConstants={
    USER_REGISTER_REQUEST:'USER_REGISTER_REQUEST',
    USER_REGISTER_SUCCESS:'USER_REGISTER_SUCCESS',
    USER_REIGISTER_FALIURE:'USER_REGISTER_FALIURE'
}

export const categoryConstants={
    GET_ALL_CATEGORY_REQUEST:"GET_ALL_CATEGORY_REQUEST",
    GET_ALL_CATEGORY_SUCCESS:"GET_ALL_CATEGORY_SUCCESS",
    GET_ALL_CATEGORY_FALIURE:"GET_ALL_CATEGORY_FALIURE",
    ADD_NEW_CATEGORY_REQUEST:"ADD_NEW_CATEGORY_REQUEST",
    ADD_NEW_CATEGORY_SUCCESS:"ADD_NEW_CATEGORY_SUCCESS",
    ADD_NEW_CATEGORY_FALIURE:"ADD_NEW_CATEGORY_FALIURE"
    
}